### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by sundowndev** [sundowndev/website#1]
- [x] contact page
- [x] resources page
- [x] base style
- [x] add public key file
- [x] Write-ups pages
- [x] add favicon
- [x] Put fonts, avatar in local files
- [x] Create config.ts
- [x] CSS animations
